import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import axios from 'axios';
import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';

function Report() {
  const [kpis, setKpis] = useState({ energy_intensity: 0, water_intensity: 0, carbon_footprint: 0 });
  const [trend, setTrend] = useState({ months: [], energy_intensity: [] });
  const [loading, setLoading] = useState(true);
  const navigate = useNavigate();

  useEffect(() => {
    const token = localStorage.getItem('token');
    if (!token) {
      navigate('/login');
      return;
    }
    fetchData();
  }, [navigate]);

  const fetchData = async () => {
    const token = localStorage.getItem('token');
    try {
      const [kpisRes, trendRes] = await Promise.all([
	axios.get('https://climafix-demo.onrender.com/api/dashboard/kpis', { params: { token } }),
	axios.get('https://climafix-demo.onrender.com/api/dashboard/trend', { params: { token } })
      ]);
      setKpis(kpisRes.data);
      setTrend(trendRes.data);
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  const generatePDF = async () => {
    const reportElement = document.getElementById('report-content');
    const canvas = await html2canvas(reportElement, { scale: 2 });
    const imgData = canvas.toDataURL('image/png');
    const pdf = new jsPDF('p', 'mm', 'a4');
    const imgWidth = 190;
    const imgHeight = (canvas.height * imgWidth) / canvas.width;
    pdf.addImage(imgData, 'PNG', 10, 10, imgWidth, imgHeight);
    pdf.save('CLIMAFIX_ESG_Report.pdf');
  };

  if (loading) return <div>Loading...</div>;

  return (
    <div style={{ padding: '20px', maxWidth: '800px', margin: '0 auto' }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '20px' }}>
        <h1 style={{ color: '#1B5E20' }}>ESG Report</h1>
        <button onClick={() => navigate('/dashboard')} style={{ padding: '8px 16px', background: '#0D9488', color: 'white', border: 'none', borderRadius: '8px', cursor: 'pointer' }}>Back to Dashboard</button>
      </div>
      
      <button onClick={generatePDF} style={{ marginBottom: '20px', padding: '10px 20px', background: '#1B5E20', color: 'white', border: 'none', borderRadius: '8px', cursor: 'pointer' }}>
        Download PDF Report
      </button>
      
      <div id="report-content" style={{ background: 'white', padding: '20px', borderRadius: '16px', border: '1px solid #e2e8f0' }}>
        <h2 style={{ color: '#1B5E20', textAlign: 'center' }}>CLIMAFIX ESG Report</h2>
        <p style={{ textAlign: 'center', color: '#5f6b7a' }}>Generated: {new Date().toLocaleString()}</p>
        <hr />
        <h3>Key Performance Indicators</h3>
        <table style={{ width: '100%', marginTop: '10px' }}>
          <thead><tr><th>Metric</th><th>Value</th></tr></thead>
          <tbody>
            <tr><td>Energy Intensity</td><td>{kpis.energy_intensity} kWh/kg</td></tr>
            <tr><td>Water Intensity</td><td>{kpis.water_intensity} L/kg</td></tr>
            <tr><td>Carbon Footprint</td><td>{kpis.carbon_footprint} tCO₂e</td></tr>
          </tbody>
        </table>
        <h3>Energy Intensity Trend</h3>
        <p>Monthly values: {trend.energy_intensity.join(' → ')} kWh/kg</p>
        <p style={{ fontSize: '12px', color: '#5f6b7a', marginTop: '20px' }}>This report is generated by CLIMAFIX DMRV platform.</p>
      </div>
    </div>
  );
}

export default Report;